{{- if and .Values.integrationTests.install .Values.integrationTests.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.integrationTests.serviceAccount.name }}
  labels:
    name: {{ .Values.integrationTests.serviceAccount.name }}
    app.kubernetes.io/name: {{ .Values.integrationTests.serviceAccount.name }}
    app.kubernetes.io/instance: {{ cat .Values.integrationTests.serviceAccount.name "-" .Release.Namespace | nospace | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: jaeger-integration-tests
    app.kubernetes.io/part-of: jaeger
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/hook-weight": "-5"
{{- end }}
